name: pokedex
description: Bayzat Pokedex home assignment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true