name: pokedex
description: Bayzat Pokedex home assignment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  animations: ^2.0.1
  infinite_scroll_pagination: ^3.2.0
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_native_splash: ^2.2.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#3558CD"
  fullscreen: true
  android_12:
    color: "#3558CD"
    icon_background_color: "#3558CD"

