name: main-ci-cd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: 'stable'
          
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generation
        run: dart run build_runner build

      - name: Run unit tests
        run: flutter test

      # Todo: release APK on GitHub
